plugins {
    id 'java-library'
    id 'net.neoforged.moddev' version '1.0.11'
}

version = "mc${minecraft_version}_v${mod_version}"
group = "mod.grimmauld.${mod_id}"
base {
    archivesName = mod_id
}

java.toolchain.languageVersion = JavaLanguageVersion.of(21)

neoForge {
    version = neo_version
    validateAccessTransformers = true

    runs {
        configureEach {
            systemProperty 'forge.logging.console.level', 'debug'
        }

        client {
            client()
        }

        server {
            server()
        }
    }

    mods {
        "${mod_id}" {
            sourceSet sourceSets.main
        }
    }
}

repositories {
    mavenCentral()
}

tasks.withType(JavaCompile).configureEach {
    options.encoding = 'UTF-8'
}

processResources {
    def replaceProperties = [
        loader_version_range   : loader_version_range,
        minecraft_version_range: minecraft_version_range,
        neo_version_range      : neo_version_range,
        mod_id                 : mod_id,
        mod_name               : mod_name,
        mod_license            : mod_license,
        mod_version            : mod_version,
        mod_authors            : mod_authors,
        mod_description        : mod_description
    ]

    inputs.properties replaceProperties

    filesMatching(['META-INF/neoforge.mods.toml']) {
        expand replaceProperties
    }
}

jar {
    manifest {
        attributes([
            'Specification-Title'     : mod_id,
            'Specification-Vendor'    : 'Grimmauld',
            'Specification-Version'   : '1',
            'Implementation-Title'    : project.name,
            'Implementation-Version'  : version,
            'Implementation-Vendor'   : 'Grimmauld',
            'Implementation-Timestamp': new Date().format("yyyy-MM-dd'T'HH:mm:ssZ")
        ])
    }
}
