modLoader = "javafml"
loaderVersion = "${loader_version_range}"
license = "${mod_license}"
#issueTrackerURL=""

[[mods]]
modId = "${mod_id}"
version = "${mod_version}"
displayName = "${mod_name}"
#updateJSONURL=""
authors = "${mod_authors}"
description = '''
${mod_description}'''

[[accessTransformers]]
file = "META-INF/accesstransformer.cfg"

[[dependencies.windowlogging]]
modId = "forge"
mandatory = true
versionRange = "${forge_version_range}"
ordering = "NONE"
side = "BOTH"

[[dependencies.windowlogging]]
modId = "minecraft"
mandatory = true
versionRange = "${minecraft_version_range}"
ordering = "NONE"
side = "BOTH"
